hub:
  image: selenium/hub
  ports:
    - "4444:4444"
  environment:
    - GRID_MAX_SESSION=10
 
firefoxdebug:
  image: selenium/node-firefox-debug::3.141
  ports:
    - 9000:5900
  environment:
    - NODE_MAX_INSTANCES=10
    - NODE_MAX_SESSION=10
  links:
    - hub

